# Generated by Django 3.0 on 2019-12-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('mId', models.IntegerField(primary_key=True, serialize=False)),
                ('matchDate', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=1000)),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('won', models.CharField(max_length=50)),
                ('tossDecision', models.CharField(max_length=50)),
                ('tossWon', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('matchType', models.CharField(choices=[('T20', 'Twenty Twenty'), ('ODI', 'One Day Internation')], default='ODI', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamBatting', models.CharField(max_length=50)),
                ('over', models.IntegerField(default=0)),
                ('ballNo', models.IntegerField(default=0)),
                ('batsman', models.CharField(max_length=500)),
                ('bowler', models.CharField(max_length=500)),
                ('runTaken', models.IntegerField(default=0)),
                ('extras', models.IntegerField(default=0)),
                ('totalRuns', models.IntegerField(default=0)),
                ('nonStriker', models.CharField(max_length=500)),
                ('mId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.Match')),
            ],
        ),
    ]
